const oracledb = require('oracledb');
const path = require('path');

require('dotenv').config({
    path: path.resolve(__dirname, '..', '.env')
});
async function createUsersTable() {
    let connection;
    try {
        connection = await oracledb.getConnection({
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: process.env.DB_CONNECT_STRING || 'localhost:1521/xepdb1'
        });
        console.log('Connected to Oracle Database');

        const createTableQuery = `
            CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(255) NOT NULL,
                email VARCHAR2(255) NOT NULL UNIQUE,
                password VARCHAR2(255) NOT NULL,
                role VARCHAR2(50) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        `;
        await connection.execute(createTableQuery);
        console.log('Table users created successfully');
    } catch (error) {
        console.error('Error creating users table:', error);
    } finally {
        if (connection) {
            try {
                await connection.close();
                console.log('Database connection closed');
            } catch (error) {
                console.error('Error closing database connection:', error);
            }
        }
    }
}

createUsersTable();